from . import bsf_config
from . import bsf_sales_to_cash
from . import bsf_bank
from . import bsf_bank_facility
from . import bsf_bank_transfer
from . import account_journal
from . import bsf_ext_fact
from . import bsf_ext_invoice
from . import bsf_ext_budget
from . import bsf_ext_account
from . import bsf_ext_gl
from . import bsf_period
from . import bsf_forecast_line
from . import bsf_billing_pattern
from . import bsf_deal
from . import bsf_forecast_snapshot
from . import bsf_risk
from . import bsf_vo
from . import bsf_source_service
from . import res_partner
from . import res_config_settings
from . import bsf_dashboard
from . import bsf_ai_service
from . import bsf_ai_chat
from . import bsf_ai_report

from . import bsf_cost
from . import bsf_strategy
from . import bsf_cost_scenario
from . import bsf_strategy_service
