{
    'name': 'Buz Dispatch Management',
    'version': '17.0.1.0.0',
    'category': 'Inventory/Delivery',
    'summary': 'Dispatch Document Management with Stock Posting Control',
    'author': 'Ball',
    'depends': [
        'stock',
        'sale_management',
        'delivery',
        'mail',
        'web',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'views/dispatch_document_views.xml',
        'views/stock_picking_views.xml',
        'views/menu.xml',
        'wizard/create_dispatch_wizard_views.xml',
        'report/dispatch_document_report.xml',
    ],
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': '_post_init_hook',
}
