/* Run only against a disposable, seeded local Odoo database. See SETUP.md. */
const testURL = process.env.IT_TEST_URL || 'http://127.0.0.1:18069';
if (!['127.0.0.1', 'localhost'].includes(new URL(testURL).hostname)) throw Error('Local test server required');
if (!process.env.IT_TEST_PASSWORD) throw Error('Set IT_TEST_PASSWORD for the disposable test account');
const {chromium}=require('playwright');
const crypto=require('crypto');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({baseURL:testURL,viewport:{width:390,height:900},hasTouch:true});
 const auth=await context.request.post('/web/session/authenticate',{data:{jsonrpc:'2.0',method:'call',params:{db:'MOG_IT_TEST',login:'admin',password:process.env.IT_TEST_PASSWORD}}});
 if((await auth.json()).error)throw Error('Authentication failed');
 const page=await context.newPage();let errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.stack)});
 page.on('console',msg=>{if(msg.type()==='error')console.error('CONSOLE',msg.text().slice(0,1000));});
 async function call(method,args){return (await (await context.request.post('/web/dataset/call_kw/buz.it.issue/'+method,{data:{jsonrpc:'2.0',method:'call',params:{model:'buz.it.issue',method,args,kwargs:{}}}})).json());}
 await page.goto('/web#action=buz_it_stock_mobile.action_it_app');
 await page.getByRole('button',{name:'เพิ่ม Logitech K120',exact:true}).click();
 await page.locator('.it-cart-bar button').click();
 await page.getByRole('button',{name:/ต่อไป · เลือกผู้รับ/}).click();
 await page.locator('.it-people button').filter({hasText:'Somchai Jaidee'}).click();
 await page.getByRole('button',{name:'ยืนยันการเบิก',exact:true}).click();
 const canvas=page.locator('canvas');await canvas.waitFor();await canvas.scrollIntoViewIfNeeded();
 const box=await canvas.boundingBox();const cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+20,y:box.y+70}]});
 for(const [x,y] of [[80,25],[50,110],[150,50],[210,100],[270,30]])await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+x,y:box.y+y}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 const signature=await canvas.evaluate(el=>el.toDataURL().split(',')[1]);
 if(await page.locator('button.it-success').isDisabled())throw Error('Touch signature not captured');
 await page.setViewportSize({width:768,height:600});
 if(await canvas.evaluate(el=>el.toDataURL().split(',')[1])!==signature)throw Error('Signature lost on rotate');
 await page.route('**/web/dataset/call_kw/buz.it.issue/action_sign',async route=>{await route.fetch();await route.abort('failed');});
 await page.locator('button.it-success').click();
 await page.getByRole('button',{name:'ตรวจสอบสถานะ',exact:true}).click();
 await page.getByRole('heading',{name:'เบิกอุปกรณ์สำเร็จ'}).waitFor();
 console.log('PASS touch signature, resize preservation, lost-response recovery');
 const people=(await call('get_people',['Somchai'])).result;
 const products=(await call('get_catalog',['Monitor'])).result.products;
 const lots=(await call('get_lots',[products[0].id])).result;
 const payload=()=>({request_key:crypto.randomUUID(),employee_id:people[0].id,lines:[{product_id:products[0].id,quantity:1,lot_id:lots[0].id}]});
 const first=(await call('save_request',[payload()])).result,second=(await call('save_request',[payload()])).result;
 const raced=await Promise.all([call('action_sign',[[first.id],signature,first.revision]),call('action_sign',[[second.id],signature,second.revision])]);
 if(raced.filter(r=>r.result?.state==='done').length!==1||raced.filter(r=>r.error).length!==1)throw Error('Serial concurrency failure '+JSON.stringify(raced));
 console.log('PASS simultaneous requests for one serial: one completion, one rejection');
 const ordinary=(await call('get_catalog',['Logitech M100'])).result.products[0];
 const third=(await call('save_request',[{request_key:crypto.randomUUID(),employee_id:people[0].id,lines:[{product_id:ordinary.id,quantity:1}]}])).result;
 const duplicates=await Promise.all([call('action_sign',[[third.id],signature,third.revision]),call('action_sign',[[third.id],signature,third.revision])]);
 if(!duplicates.every(r=>r.result?.state==='done')||duplicates[0].result.picking_id!==duplicates[1].result.picking_id)throw Error('Duplicate concurrency failure '+JSON.stringify(duplicates));
 console.log('PASS simultaneous duplicate confirmation: same picking returned');
 console.log('Browser errors',errors);
 if(errors.length) throw Error('Unexpected browser errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
