{
    "name": "Lazada Odoo Connector",
    "version": "17.0.1.0.0",
    "category": "Sales/Sales",
    "summary": "Full Lazada Open Platform Integration",
    "author": "Custom Developer",
    "license": "LGPL-3",
    "depends": ["sale_management", "stock", "website"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "views/lazada_menu.xml",
        "views/lazada_config_views.xml",
        "views/sale_order_views.xml",
        "views/product_views.xml",
        "views/lazada_log_views.xml",
        "views/lazada_product_mapping_views.xml",
        "views/lazada_stock_import_views.xml",
    ],
    "installable": True,
    "application": True,
    "icon": "/lazada_odoo_connector/static/description/icon.png",
    "web_icon": "lazada_odoo_connector,static/description/icon.png",
}