{
    "name": "Lazada Odoo Connector",
    "version": "17.0.2.0.0",
    "category": "Sales/Sales",
    "summary": "Full Lazada Open Platform Integration",
    "author": "Custom Developer",
    "license": "LGPL-3",
    "depends": ["sale_management", "stock", "website"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/lazada_security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/lazada_order_tags.xml",
        "security/lazada_fulfillment_rules.xml",
        "data/lazada_fulfillment_cron.xml",
        "views/lazada_menu.xml",
        "views/lazada_dashboard_views.xml",
        "views/lazada_config_views.xml",
        "views/sale_order_views.xml",
        "views/lazada_fulfillment_views.xml",
        "views/product_views.xml",
        "views/lazada_log_views.xml",
        "views/lazada_product_mapping_views.xml",
        "views/lazada_stock_import_views.xml",
        "views/lazada_mapping_import_views.xml",
        "views/lazada_order_sync_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "lazada_connector/static/src/**/*",
        ],
    },
    "installable": True,
    "application": True,
    "icon": "/lazada_connector/static/description/icon.png",
    "web_icon": "lazada_connector,static/description/icon.png",
}
