from . import shopee_api
from . import shopee_config
from . import sale_order
from . import sale_order_line
from . import product_template
from . import res_partner
from . import shopee_log
from . import shopee_product_mapping
from . import shopee_fulfillment
