{
    "name": "Marketplace Settlement",
    "summary": "Wizard to group many customer invoices into a single receivable to marketplace (e.g., Shopee)",
    "version": "17.0.1.0.0",
    "author": "Ball + Manow",
    "category": "Accounting/Localizations",
    "website": "https://example.com",
    "license": "LGPL-3",
    "icon": "static/description/icon.png",
    "depends": ["account", "sale"],
    'data': [
        'security/ir.model.access.csv',
        'data/marketplace_settlement_profile_data.xml',
        'views/marketplace_vendor_bill_views.xml',
        'views/profile_views.xml',
        'views/marketplace_netting_wizard_views.xml',
        'views/account_move_view_inherit.xml',
        'views/sale_order_view_inherit.xml',
        'views/marketplace_fee_allocation_views.xml',
        'views/marketplace_fee_allocation_import_wizard_views.xml',
        'views/marketplace_fee_allocation_report_views.xml',
        'views/settlement_preview_wizard_views.xml',
        'views/marketplace_settlement_wizard_views.xml',
    ],
    "demo": [
        "data/demo_data.xml",
        "data/demo_vendor_bills.xml",
        "data/demo_fee_allocations.xml",
    ],
    # Custom JS assets removed temporarily to avoid webclient break while debugging
    "installable": True,
    "application": False,
}
