# -*- coding: utf-8 -*-
{    "name": "MOG Expense: Petty Cash, Advance & Clearing (Odoo 17)",
    "summary": "Petty cash boxes, advances/clearing, configurable posting journal, and VAT option (include or separate tax lines).",
    "version": "17.0.4.0.0",
    "author": "Ball & Lime (มะนาว)",
    "website": "https://example.invalid",
    "license": "LGPL-3",
    "category": "Accounting/Expenses",
    "depends": ["hr_expense", "account", "contacts", "l10n_th_account_tax"],
    "data": [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizard/advance_clear_wizard_views.xml',
        'wizard/petty_cash_replenish_wizard_views.xml',
        'views/petty_cash_box_views.xml',
        'views/advance_request_views.xml',
        'views/clearing_views.xml',
        'views/hr_expense_sheet_views_inherit.xml',
        'views/res_config_settings_views.xml',
        'views/menu.xml',
    ],
    "installable": True,
    "application": True,
}
