{
    "name": "BUZ IT Helpdesk",
    "version": "17.0.1.3.0",
    "category": "Services/Helpdesk",
    "summary": "Standalone IT Helpdesk for BUZ IT Management Phase 1",
    "author": "Mogen Co.",
    "license": "LGPL-3",
    "depends": ["base", "mail", "portal", "website"],
    "data": [
        "security/security.xml",
        "security/helpdesk_extra_security.xml",
        "security/it_asset_security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/helpdesk_data.xml",
        'data/helpdesk_migration.xml',
        "data/it_asset_data.xml",
        "views/helpdesk_views.xml",
        "views/it_asset_views.xml",
        "views/helpdesk_menus.xml",
        "views/helpdesk_team_views.xml",
        "views/helpdesk_report_views.xml",
        "views/helpdesk_portal_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "buz_it_helpdesk/static/src/js/helpdesk_activity_auto_clear.js",
            "buz_it_helpdesk/static/src/js/helpdesk_attachment_preview_field.js",
            "buz_it_helpdesk/static/src/js/helpdesk_dashboard.js",
            "buz_it_helpdesk/static/src/xml/helpdesk_attachment_preview_field.xml",
            "buz_it_helpdesk/static/src/xml/helpdesk_dashboard.xml",
            "buz_it_helpdesk/static/src/css/helpdesk_dashboard.css",
        ],
    },
    "application": True,
    "installable": True,
}
