{
    'name': 'IT Asset',
    'version': '17.0.1.5.0',
    'category': 'Services/IT',
    'summary': 'Hardware and software asset registry for IT Management',
    'author': 'BUZ',
    'license': 'LGPL-3',
    'depends': ['buz_it_helpdesk', 'hr', 'mail'],
    'data': [
        'data/hardware_taxonomy.xml',
        'data/asset_spec_profiles.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/asset_views.xml',
        'views/asset_type_views.xml',
        'views/software_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
}
