{
    "name": "BUZ ISO Document Control",
    "summary": "ISO document distribution and revision control",
    "version": "17.0.1.2.0",
    "category": "Documents",
    "author": "Mogen Co., Ltd.",
    "license": "LGPL-3",
    "depends": ["base", "mail", "web", "hr"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/document_type_data.xml",
        "data/ir_cron_data.xml",
        "views/document_views.xml",
        "views/document_revision_views.xml",
        "views/document_type_views.xml",
        "views/document_category_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/document_revision_wizard_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "buz_document_control/static/src/js/document_components.js",
            "buz_document_control/static/src/js/document_dashboard.js",
            "buz_document_control/static/src/js/document_viewer.js",
            "buz_document_control/static/src/xml/document_components.xml",
            "buz_document_control/static/src/xml/document_dashboard.xml",
            "buz_document_control/static/src/xml/document_viewer.xml",
            "buz_document_control/static/src/scss/document_control.scss",
            "buz_document_control/static/src/scss/document_dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
