{
    "name": "Shopee Odoo Connector",
    "version": "17.0.2.18.0",
    "category": "Sales/Sales",
    "summary": "Full Shopee Open Platform v2 Integration",
    "author": "Custom Developer",
    "license": "LGPL-3",
    "depends": ["sale_management", "stock", "website"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/shopee_order_tags.xml",
        "security/shopee_fulfillment_rules.xml",
        "data/shopee_fulfillment_cron.xml",
        "views/shopee_menu.xml",
        "views/shopee_config_views.xml",
        "views/sale_order_views.xml",
        "views/shopee_fulfillment_views.xml",
        "views/product_views.xml",
        "views/shopee_log_views.xml",
        "views/shopee_product_mapping_views.xml",
        "views/shopee_stock_import_views.xml",
        "views/shopee_buyer_address_import_views.xml",
        "views/shopee_order_sync_views.xml",
    ],
    "installable": True,
    "application": True,
    "icon": "/shopee_connector/static/description/icon.png",
    "web_icon": "shopee_connector,static/description/icon.png",
}