# Part of buz addons for Mogen Co. See LICENSE file.
from odoo import _, api, fields, models
from odoo.exceptions import ValidationError
from odoo.tools import float_compare, float_is_zero


class BuzReverseRecoveryLine(models.Model):
    """One component expected to be recovered by a Reverse MO.

    Lines are generated by exploding the reverse BOM when product, BOM and
    quantity are set on the order. Before the order is marked done the user
    can adjust the recovered quantity, the destination location and the
    lot/serial. The allocation engine writes ``allocation_percent`` which is
    propagated to the ``cost_share`` of the generated finished move.
    """

    _name = 'buz.reverse.recovery.line'
    _description = 'Reverse Manufacturing Recovery Line'
    _order = 'sequence, id'

    production_id = fields.Many2one(
        'mrp.production',
        string='Reverse Manufacturing Order',
        required=True,
        ondelete='cascade',
        index=True,
    )
    sequence = fields.Integer(default=10)
    bom_line_id = fields.Many2one(
        'mrp.bom.line',
        string='BOM Line',
        readonly=True,
        help='Reverse BOM line this recovered component comes from.',
    )
    product_id = fields.Many2one(
        'product.product',
        string='Recovered Product',
        required=True,
        check_company=True,
    )
    product_uom_id = fields.Many2one(
        'uom.uom',
        string='Unit of Measure',
        required=True,
    )
    product_uom_category_id = fields.Many2one(
        related='product_id.uom_id.category_id')
    tracking = fields.Selection(related='product_id.tracking')
    expected_qty = fields.Float(
        string='Expected Qty',
        digits='Product Unit of Measure',
        readonly=True,
        help='Quantity from the reverse BOM (BOM line quantity x order '
             'quantity), before applying the recovery percentage.',
    )
    recovery_percent = fields.Float(
        string='Recovery %',
        default=100.0,
        digits=(5, 2),
        help='Percentage of the expected quantity recovered in good '
             'condition. Changing it recomputes the actual quantity.',
    )
    actual_qty = fields.Float(
        string='Actual Qty',
        digits='Product Unit of Measure',
        help='Quantity actually recovered and put in the destination '
             'location. The shortfall against the expected quantity is '
             'scrapped when the scrap policy is "Auto Scrap Shortfall".',
    )
    scrap_qty = fields.Float(
        string='Scrap Qty',
        digits='Product Unit of Measure',
        compute='_compute_scrap_qty',
        store=True,
        help='Expected quantity minus actual quantity (never negative).',
    )
    scrap_policy = fields.Selection(
        [('auto', 'Auto Scrap Shortfall'), ('none', 'No Scrap')],
        string='Scrap Policy',
        default='auto',
        required=True,
    )
    destination_location_id = fields.Many2one(
        'stock.location',
        string='Destination Location',
        domain="[('usage', '=', 'internal')]",
        check_company=True,
        required=True,
        help='Internal location where this recovered component is put away.',
    )
    lot_id = fields.Many2one(
        'stock.lot',
        string='Lot/Serial',
        domain="[('product_id', '=', product_id)]",
        check_company=True,
        help='Lot/serial assigned to the recovered quantity for tracked '
             'products. Required before marking the order done.',
    )
    # Cost allocation
    allocation_percent = fields.Float(
        string='Allocation %',
        digits=(5, 2),
        readonly=True,
        help='Share of the total recoverable cost allocated to this line. '
             'Computed by the allocation engine; the sum over all lines '
             'with a positive actual quantity is exactly 100.',
    )
    manual_percent = fields.Float(
        string='Manual %',
        digits=(5, 2),
        help='Allocation percentage entered by the user (method '
             '"Percentage"). All lines must add up to 100.',
    )
    manual_amount = fields.Monetary(
        string='Manual Amount',
        currency_field='currency_id',
        help='Cost amount entered by the user (method "Manual Amount"). '
             'Amounts are normalized to allocation percentages.',
    )
    calculated_cost = fields.Monetary(
        string='Calculated Cost',
        currency_field='currency_id',
        readonly=True,
        help='Allocation % x total recoverable cost, computed when the '
             'order is validated.',
    )
    final_cost = fields.Monetary(
        string='Final Cost',
        currency_field='currency_id',
        compute='_compute_final_cost',
        help='Actual value of the stock valuation layer created for this '
             'line once the order is done.',
    )
    move_id = fields.Many2one(
        'stock.move',
        string='Stock Move',
        readonly=True,
        copy=False,
    )
    scrap_id = fields.Many2one(
        'stock.scrap',
        string='Scrap',
        readonly=True,
        copy=False,
    )
    currency_id = fields.Many2one(related='production_id.company_id.currency_id')
    company_id = fields.Many2one(
        related='production_id.company_id',
        store=True,
        index=True,
    )
    state = fields.Selection(related='production_id.state', store=True)

    _AUDITED_FIELDS = {
        'actual_qty': 'Actual Qty',
        'recovery_percent': 'Recovery %',
        'destination_location_id': 'Destination Location',
        'manual_percent': 'Manual %',
        'manual_amount': 'Manual Amount',
        'lot_id': 'Lot/Serial',
    }

    @api.depends('expected_qty', 'actual_qty')
    def _compute_scrap_qty(self):
        for line in self:
            line.scrap_qty = max(0.0, line.expected_qty - line.actual_qty)

    @api.depends('move_id.stock_valuation_layer_ids.value')
    def _compute_final_cost(self):
        for line in self:
            line.final_cost = sum(
                line.move_id.sudo().stock_valuation_layer_ids.mapped('value'))

    @api.onchange('product_id')
    def _onchange_product_id(self):
        if self.product_id:
            self.product_uom_id = self.product_id.uom_id

    @api.onchange('recovery_percent', 'expected_qty')
    def _onchange_recovery_percent(self):
        self.actual_qty = self.expected_qty * self.recovery_percent / 100.0

    @api.constrains('actual_qty', 'expected_qty')
    def _check_quantities(self):
        for line in self:
            if float_compare(line.actual_qty, 0.0,
                             precision_rounding=line.product_uom_id.rounding or 0.01) < 0:
                raise ValidationError(_('The actual quantity cannot be negative.'))

    @api.constrains('destination_location_id')
    def _check_destination_location(self):
        for line in self:
            if line.destination_location_id.usage != 'internal':
                raise ValidationError(_(
                    'The destination location of %s must be an internal '
                    'location.') % line.product_id.display_name)

    def write(self, vals):
        # Audit trail: post edits of business-critical fields to the
        # order's chatter (same pattern as buz_mrp_unbuild_enhancement).
        tracked = [f for f in self._AUDITED_FIELDS if f in vals]
        old_values = {}
        if tracked:
            old_values = {
                line.id: {f: line[f] for f in tracked} for line in self
            }
        res = super().write(vals)
        if tracked:
            for line in self:
                changes = []
                for field_name in tracked:
                    old = old_values[line.id][field_name]
                    new = line[field_name]
                    if old == new:
                        continue
                    if isinstance(old, models.BaseModel):
                        old = old.display_name or _('(empty)')
                        new = new.display_name or _('(empty)')
                    changes.append('%s: %s → %s' % (
                        _(self._AUDITED_FIELDS[field_name]), old, new))
                if changes:
                    line.production_id.message_post(
                        body=_('Recovery line %s updated:\n%s') % (
                            line.product_id.display_name, '\n'.join(changes)),
                        subtype_xmlid='mail.mt_note',
                    )
        return res

    def _get_allocation_basis(self, method):
        """Return this line's raw weight for the given allocation method."""
        self.ensure_one()
        if method == 'bom_cost':
            return self.product_id.standard_price * self.actual_qty
        if method == 'percentage':
            return self.manual_percent
        if method == 'quantity':
            return self.product_uom_id._compute_quantity(
                self.actual_qty, self.product_id.uom_id)
        if method == 'weight':
            return self.product_id.weight * self.actual_qty
        if method == 'manual':
            return self.manual_amount
        return 0.0

    def _is_zero_basis(self, method, value):
        precision = 4 if method != 'percentage' else 2
        return float_is_zero(value, precision_digits=precision)
