"""
Tests for forecast.plan model.

Tests cover plan creation, uniqueness constraints, state workflow,
computed fields, and business validations.
"""

from dateutil.relativedelta import relativedelta

from odoo import fields
from odoo.exceptions import ValidationError
from odoo.tests import tagged

from .common import ForecastTestCommon


@tagged("post_install", "-at_install")
class TestForecastPlanCreation(ForecastTestCommon):
    """Test forecast plan creation and auto-generated values."""

    def test_create_plan_with_defaults(self):
        """Create plan with default values - user should default to current user, start_date to first of month."""
        plan = self.env["forecast.plan"].create({})

        self.assertEqual(plan.state, "draft")
        self.assertEqual(plan.user_id, self.env.user)
        self.assertEqual(plan.start_date, self.get_current_month_start())
        self.assertEqual(plan.company_id, self.company)

    def test_create_plan_with_specific_user(self):
        """Create plan with specific user assignment."""
        plan = self.create_forecast_plan(user=self.user_sales)

        self.assertEqual(plan.user_id, self.user_sales)

    def test_create_plan_generates_sequence(self):
        """Verify plan name is auto-generated by sequence on create."""
        plan = self.create_forecast_plan()

        self.assertNotEqual(plan.name, "New")
        self.assertTrue(plan.name.startswith(("FP", "FPL", "PLAN", "FS")))

    def test_create_multiple_plans_have_unique_names(self):
        """Verify multiple plans get unique sequence numbers."""
        plan1 = self.create_forecast_plan()
        plan2 = self.create_forecast_plan(user=self.user_sales)

        self.assertNotEqual(plan1.name, plan2.name)

    def test_create_plan_with_blanket_reference(self):
        """Create plan with blanket PO reference."""
        blanket_ref = "PO-2024-001"
        plan = self.create_forecast_plan()
        plan.write({"blanket_reference": blanket_ref})

        self.assertEqual(plan.blanket_reference, blanket_ref)

    def test_create_plan_with_custom_start_date(self):
        """Create plan with custom start date (must be first of month)."""
        custom_date = self.get_next_month_start(months=2)
        plan = self.create_forecast_plan(start_date=custom_date)

        self.assertEqual(plan.start_date, custom_date)


@tagged("post_install", "-at_install")
class TestForecastPlanEndDate(ForecastTestCommon):
    """Test end_date computation (start_date + 3 months - 1 day)."""

    def test_end_date_computed_from_start_date(self):
        """Verify end_date = start_date + 3 months - 1 day."""
        start_date = self.get_current_month_start()
        plan = self.create_forecast_plan(start_date=start_date)

        expected_end = start_date + relativedelta(months=3, days=-1)
        self.assertEqual(plan.end_date, expected_end)

    def test_end_date_updates_when_start_date_changes(self):
        """Verify end_date recomputes when start_date is updated."""
        plan = self.create_forecast_plan()
        original_end = plan.end_date

        new_start = self.get_next_month_start(months=1)
        plan.write({"start_date": new_start})

        expected_end = new_start + relativedelta(months=3, days=-1)
        self.assertNotEqual(plan.end_date, original_end)
        self.assertEqual(plan.end_date, expected_end)


@tagged("post_install", "-at_install")
class TestForecastPlanUniquenessConstraint(ForecastTestCommon):
    """Test SQL constraint: 1 plan per user per month per company."""

    def test_one_plan_per_user_per_month_allowed(self):
        """Create 1 plan for user/month/company - should succeed."""
        user = self.user_planner
        month_start = self.get_current_month_start()

        plan1 = self.create_forecast_plan(user=user, start_date=month_start)
        self.assertTrue(plan1.id)

        # Second plan for same user/month should fail
        with self.assertRaises(ValidationError) as cm:
            self.env["forecast.plan"].create({
                "user_id": user.id,
                "start_date": month_start,
                "company_id": self.company.id,
            })

        self.assertIn("Only one forecast plan is allowed per user per month", str(cm.exception))

    def test_multiple_plans_different_months_allowed(self):
        """Create plans for same user but different months - should succeed."""
        user = self.user_planner
        month1 = self.get_current_month_start()
        month2 = self.get_next_month_start(months=1)

        plan1 = self.create_forecast_plan(user=user, start_date=month1)
        plan2 = self.create_forecast_plan(user=user, start_date=month2)

        self.assertTrue(plan1.id)
        self.assertTrue(plan2.id)
        self.assertEqual(plan1.user_id, plan2.user_id)
        self.assertNotEqual(plan1.start_date, plan2.start_date)

    def test_multiple_plans_different_users_same_month_allowed(self):
        """Create plans for different users in same month - should succeed."""
        month_start = self.get_current_month_start()

        plan1 = self.create_forecast_plan(user=self.user_planner, start_date=month_start)
        plan2 = self.create_forecast_plan(user=self.user_sales, start_date=month_start)

        self.assertTrue(plan1.id)
        self.assertTrue(plan2.id)
        self.assertNotEqual(plan1.user_id, plan2.user_id)
        self.assertEqual(plan1.start_date, plan2.start_date)

    def test_multiple_plans_different_companies_allowed(self):
        """Create plans for same user/month but different companies - should succeed."""
        # Create a second company
        company2 = self.env["res.company"].create({
            "name": "Test Company 2",
        })

        user = self.user_planner
        month_start = self.get_current_month_start()

        plan1 = self.create_forecast_plan(user=user, start_date=month_start)
        plan2 = self.env["forecast.plan"].create({
            "user_id": user.id,
            "start_date": month_start,
            "company_id": company2.id,
        })

        self.assertTrue(plan1.id)
        self.assertTrue(plan2.id)
        self.assertNotEqual(plan1.company_id, plan2.company_id)


@tagged("post_install", "-at_install")
class TestForecastPlanStartDateValidation(ForecastTestCommon):
    """Test validation: start_date must be first day of month."""

    def test_start_date_first_of_month_allowed(self):
        """Create plan with start_date = first of month - should succeed."""
        first_of_month = self.get_current_month_start()

        plan = self.create_forecast_plan(start_date=first_of_month)
        self.assertTrue(plan.id)

    def test_start_date_not_first_of_month_fails(self):
        """Create plan with start_date != first of month - should fail."""
        from datetime import date

        # Try with 2nd day of month
        second_of_month = date(2024, 1, 2)

        with self.assertRaises(ValidationError) as cm:
            self.create_forecast_plan(start_date=second_of_month)

        self.assertIn("Forecast Start Date must be the first day of a month", str(cm.exception))


@tagged("post_install", "-at_install")
class TestForecastPlanStateWorkflow(ForecastTestCommon):
    """Test state transitions: draft -> confirmed -> done/cancel."""

    def test_default_state_is_draft(self):
        """New plan should start in draft state."""
        plan = self.create_forecast_plan()

        self.assertEqual(plan.state, "draft")

    def test_draft_to_confirmed(self):
        """Transition from draft to confirmed."""
        plan = self.create_forecast_plan(state="draft")

        plan.action_confirm()

        self.assertEqual(plan.state, "confirmed")

    def test_confirmed_to_done(self):
        """Transition from confirmed to done."""
        plan = self.create_forecast_plan(state="confirmed")

        plan.action_done()

        self.assertEqual(plan.state, "done")

    def test_draft_to_done(self):
        """Direct transition from draft to done."""
        plan = self.create_forecast_plan(state="draft")

        plan.action_done()

        self.assertEqual(plan.state, "done")

    def test_any_state_to_cancel(self):
        """Cancel from any state."""
        for initial_state in ["draft", "confirmed", "done"]:
            plan = self.create_forecast_plan(state=initial_state)

            plan.action_cancel()

            self.assertEqual(plan.state, "cancel")

    def test_cancelled_to_draft(self):
        """Reset cancelled plan back to draft."""
        plan = self.create_forecast_plan(state="cancel")

        plan.action_set_draft()

        self.assertEqual(plan.state, "draft")

    def test_confirmed_to_draft_via_cancel(self):
        """Reset confirmed plan back to draft via cancel."""
        plan = self.create_forecast_plan(state="confirmed")

        plan.action_cancel()
        plan.action_set_draft()

        self.assertEqual(plan.state, "draft")


@tagged("post_install", "-at_install")
class TestForecastPlanTotals(ForecastTestCommon):
    """Test total calculations: forecast, allocated, actual sold."""

    def test_total_forecast_qty_with_no_lines(self):
        """Plan with no lines should have total_forecast_qty = 0."""
        plan = self.create_forecast_plan()

        self.assertEqual(plan.total_forecast_qty, 0.0)

    def test_total_forecast_qty_with_lines(self):
        """Total forecast qty should sum all line forecast_qtys."""
        plan = self.create_forecast_plan()

        line1 = self.create_forecast_line(plan, self.product_a, 50)
        line2 = self.create_forecast_line(plan, self.product_b, 30)
        line3 = self.create_forecast_line(plan, self.product_c, 20)

        # Trigger recompute
        plan.invalidate_recordset()

        self.assertEqual(plan.total_forecast_qty, 100.0)

    def test_total_allocated_qty_with_no_allocations(self):
        """Plan with no allocations should have total_allocated_qty = 0."""
        plan = self.create_forecast_plan()
        self.create_forecast_line(plan, self.product_a, 100)

        self.assertEqual(plan.total_allocated_qty, 0.0)

    def test_total_allocated_qty_with_allocations(self):
        """Total allocated qty should sum all line allocated_qtys."""
        plan = self.create_forecast_plan()
        line = self.create_forecast_line(plan, self.product_a, 100)

        # Create sale order and allocation
        so = self.create_sale_order(user=plan.user_id, lines=[(self.product_a, 30)])
        so.action_confirm()

        # Trigger recompute
        plan.invalidate_recordset()

        self.assertGreater(plan.total_allocated_qty, 0)

    def test_total_actual_sold_qty_with_no_deliveries(self):
        """Plan with no deliveries should have total_actual_sold_qty = 0."""
        plan = self.create_forecast_plan()
        self.create_forecast_line(plan, self.product_a, 100)

        self.assertEqual(plan.total_actual_sold_qty, 0.0)

    def test_total_actual_sold_qty_with_deliveries(self):
        """Total actual sold should sum all line actual_sold_qtys."""
        plan = self.create_forecast_plan(user=self.user_sales)
        line = self.create_forecast_line(plan, self.product_a, 100)

        # Create and confirm sale order
        so = self.create_sale_order(
            user=self.user_sales,
            lines=[(self.product_a, 30)]
        )
        so.action_confirm()

        # Mark as delivered
        if so.order_line:
            so.order_line[0].write({"qty_delivered": 30})

        # Trigger recompute
        plan.invalidate_recordset()

        self.assertGreater(plan.total_actual_sold_qty, 0)


@tagged("post_install", "-at_install")
class TestForecastPlanRates(ForecastTestCommon):
    """Test allocation rate and accuracy rate computations."""

    def test_allocation_rate_with_no_forecast(self):
        """Zero forecast should result in allocation_rate = 0 (no division by zero)."""
        plan = self.create_forecast_plan()

        self.assertEqual(plan.total_forecast_qty, 0.0)
        self.assertEqual(plan.allocation_rate, 0.0)

    def test_allocation_rate_partial_allocation(self):
        """Allocation rate = (allocated / forecast * 100)."""
        plan = self.create_forecast_plan()
        self.create_forecast_line(plan, self.product_a, 100)

        # Create allocation for 30 units
        so = self.create_sale_order(user=plan.user_id, lines=[(self.product_a, 30)])
        so.action_confirm()

        # Trigger recompute
        plan.invalidate_recordset()

        # Rate should be 30%
        self.assertAlmostEqual(plan.allocation_rate, 30.0, places=1)

    def test_allocation_rate_full_allocation(self):
        """Full allocation should result in allocation_rate = 100%."""
        plan = self.create_forecast_plan(user=self.user_sales)
        self.create_forecast_line(plan, self.product_a, 100)

        # Create sale order for full forecast qty
        so = self.create_sale_order(
            user=self.user_sales,
            lines=[(self.product_a, 100)]
        )
        so.action_confirm()

        # Trigger recompute
        plan.invalidate_recordset()

        self.assertAlmostEqual(plan.allocation_rate, 100.0, places=1)

    def test_accuracy_rate_with_no_forecast(self):
        """Zero forecast should result in accuracy_rate = 0 (no division by zero)."""
        plan = self.create_forecast_plan()

        self.assertEqual(plan.total_forecast_qty, 0.0)
        self.assertEqual(plan.accuracy_rate, 0.0)

    def test_accuracy_rate_partial_sales(self):
        """Accuracy rate = (actual sold / forecast * 100)."""
        plan = self.create_forecast_plan(user=self.user_sales)
        self.create_forecast_line(plan, self.product_a, 100)

        # Create and confirm sale
        so = self.create_sale_order(
            user=self.user_sales,
            lines=[(self.product_a, 40)]
        )
        so.action_confirm()

        # Mark as delivered
        if so.order_line:
            so.order_line[0].write({"qty_delivered": 40})

        # Trigger recompute
        plan.invalidate_recordset()

        # Accuracy should be 40%
        self.assertAlmostEqual(plan.accuracy_rate, 40.0, places=1)


@tagged("post_install", "-at_install")
class TestForecastPlanWeeklyDistribution(ForecastTestCommon):
    """Test weekly distribution functionality."""

    def test_action_distribute_weekly_applies_to_all_lines(self):
        """action_distribute_weekly should distribute all plan lines evenly."""
        plan = self.create_forecast_plan()

        line1 = self.create_forecast_line(plan, self.product_a, 100, apply_distribution=False)
        line2 = self.create_forecast_line(plan, self.product_b, 50, apply_distribution=False)

        # Clear any existing distribution
        line1.write({"week1_qty": 0, "week2_qty": 0, "week3_qty": 0, "week4_qty": 0, "week5_qty": 0})
        line2.write({"week1_qty": 0, "week2_qty": 0, "week3_qty": 0, "week4_qty": 0, "week5_qty": 0})

        # Trigger distribution
        plan.action_distribute_weekly()

        # Check that weeks are populated
        for line in [line1, line2]:
            total_weeks = line.week1_qty + line.week2_qty + line.week3_qty + line.week4_qty + line.week5_qty
            self.assertAlmostEqual(total_weeks, line.forecast_qty, places=2)

    def test_action_distribute_weekly_on_empty_plan(self):
        """action_distribute_weekly on plan with no lines should not crash."""
        plan = self.create_forecast_plan()

        # Should not raise any exception
        plan.action_distribute_weekly()


@tagged("post_install", "-at_install")
class TestForecastPlanActions(ForecastTestCommon):
    """Test plan actions and button handlers."""

    def test_action_view_lines_analysis(self):
        """action_view_lines_analysis should return action with correct domain."""
        plan = self.create_forecast_plan()
        self.create_forecast_line(plan, self.product_a, 100)

        action = plan.action_view_lines_analysis()

        self.assertEqual(action["res_model"], "forecast.line")
        self.assertIn(("plan_id", "=", plan.id), action["domain"])


@tagged("post_install", "-at_install")
class TestForecastPlanChatterTracking(ForecastTestCommon):
    """Test that chatter tracking works for important fields."""

    def test_state_change_tracked(self):
        """State changes should appear in chatter messages."""
        plan = self.create_forecast_plan()

        initial_msg_count = len(plan.message_ids)

        plan.action_confirm()

        self.assertEqual(len(plan.message_ids), initial_msg_count + 1)

    def test_user_change_tracked(self):
        """User changes should be tracked."""
        plan = self.create_forecast_plan()

        initial_msg_count = len(plan.message_ids)

        plan.write({"user_id": self.user_sales.id})

        self.assertGreater(len(plan.message_ids), initial_msg_count)
