from . import product_template
from . import product
from . import res_partner
from . import warranty_card
from . import warranty_claim
from . import warranty_claim_line
from . import warranty_dashboard
from . import stock_picking
from . import res_config_settings
